### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [iv522-sibsutis/crypt#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:
1. В [wiki](https://github.com/iv522-sibsutis/crypt/wiki) проекта написана статья с ТЗ.
2. В [issues](https://github.com/iv522-sibsutis/crypt/issues) созданы задачи.
3. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by umorw** [comment]
Готово

To: @evgeny-p

**Comment by evgeny-p** [comment]
> После выбора алгоритма, программа запрашивает ввод данных (текст) для шифрования

Почему обязательно после? Как Вы представляете интерфейс приложения? Wizard-like с кнопками next-next-next? Если реализовать единственное окно с группой контролов radio button и текстовым полем, то последовательность ввода может быть любой.

На чем планируется реализовывать интерфейс?

**Comment by umorw** [comment]
на GTK, напишем, когда сам алгоритм готов будет

**Comment by evgeny-p** [comment]
В таком случае должно быть как минимум консольное приложение на первой итерации. Это нужно задокументировать в ТЗ, описать формат аргументов командной строки и поведение, завести задачу на разработку.

**Comment by umorw** [comment]
Пожалуйста, посмотрите wiki
