### ISSUE TITLE
Ошибки в работе алгоритма Вижинера

### ISSUE THREAD

**Issue by umorw** [iv522-sibsutis/crypt#9]
Необходимо разобраться с неправильной дешифровкой алгоритма, а так же разбить на функцию шифрования и дешифрования

**Comment by umorw** [comment]
Проблема решена, осталось разбить на 2 функции
To: @evgeny-p

**Comment by evgeny-p** [comment]
В исходной формулировке две задачи:
1. Исправление ошибки.
2. Рефакторинг.

Предлагаю в этой задаче оставить только часть, соответствующую ошибке, и закрыть, а рефакторинг вынести в отдельную задачу.

Последний комментарий был адресован мне, но не совсем ясно: какое ожидается участие с моей стороны.

**Comment by umorw** [comment]
Ну вы же все равно проверяете
